### PR TITLE
travis-ci support for python 3

### PR DESCRIPTION
**Pull request by themperek**
Hi,
It seems to work but there are some errors (see https://travis-ci.org/themperek/cocotb/jobs/46778721)
Maybe something with LD_LIBRARY_PATH too.
Tomek
PS. Maybe should add '"or report['success'] == 0" to indcate failure in report_results.py

### CODE REVIEW

**Comment by jeremyherbert** [comment]
Thanks. I will fix this up today. It's definitely a LD_LIBRARY_PATH problem

**Comment by themperek** [comment]
Some diffrent errors: https://travis-ci.org/themperek/cocotb/jobs/46834574
Maybe better fix this in the Makefile

**Comment by jeremyherbert** [comment]
yep working on it now. The problem is that it is building with libpython3.4.so instead of libpython3.4m.so

**Comment by themperek** [comment]
make help https://github.com/themperek/cocotb/compare/jeremyherbert:master...master

**Comment by jeremyherbert** [comment]
added them, thanks. I've also filed an issue with the travis-ci folks: https://github.com/travis-ci/travis-ci/issues/3107

**Pull request merged**
